from .usuarios import Usuario as UsuarioResource
from .usuarios import Usuarios as UsuariosResource
from .productos import Producto as ProductoResource
from .productos import Productos as ProductosResource
from .pedidos import Pedido as PedidoResource
from .pedidos import Pedidos as PedidosResource
from .notificaciones import Notificacion as NotificacionResource
from .valoraciones import Valoracion as ValoracionResource
from .valoraciones import Valoraciones as ValoracionesResource
